Repository slds-lmu/lecture_i2ml, pull requests merged in 2021-12, with the labels that each got.

#704 drafted second eval exercise
  exercises-pdf/ex_eval_2.pdf
  exercises-pdf/sol_eval_2.pdf
  exercises/evaluation/collection_eval.Rnw
  exercises/evaluation/ex_eval_2.Rnw
  exercises/evaluation/ex_rnw/ex_of_uf.Rnw
  exercises/evaluation/ex_rnw/ex_resa_mlr3.Rnw
  exercises/evaluation/ex_rnw/sol_of_uf.Rnw
  exercises/evaluation/ex_rnw/sol_of_uf.tex
  exercises/evaluation/ex_rnw/sol_resa_mlr3.Rnw
  exercises/evaluation/sol_eval_2.Rnw
Labels: chap-eval, exercises

#707 added bayes-optimal model
  cheatsheets/cheatsheet_notation/beamerthememlr.sty
  cheatsheets/cheatsheet_notation/cheatsheet_notation.pdf
  cheatsheets/cheatsheet_notation/cheatsheet_notation.tex
Labels: hiwi

#714 Small Changes IC week #7
  exercises/evaluation/ex_rnw/ex_make_up_questions.Rnw
Labels: hiwi, inv-classroom

#703 Finished cleaning up chapter 13: information theory
  slides/information-theory/figure/ambiguity.png
  slides/information-theory/figure/binom1.png
  slides/information-theory/figure/binom2.png
  slides/information-theory/figure/codetree1.png
  slides/information-theory/figure/codetree2.png
  slides/information-theory/figure/coin_entropy.png
  slides/information-theory/figure/coin_entropy2.png
  slides/information-theory/figure/corr.png
  slides/information-theory/figure/correlation_plot.png
  slides/information-theory/figure/crossent.png
  slides/information-theory/figure/diffent-quant.png
  slides/information-theory/figure/entropy-binary-plot-1.pdf
  slides/information-theory/figure/entropy_plot.png
  slides/information-theory/figure/entropy_uniform_plot.png
  slides/information-theory/figure/equal_decode.png
  slides/information-theory/figure/forward_kl.png
  slides/information-theory/figure/kl_example.png
  slides/information-theory/figure/kl_log_diff_plot.png
  slides/information-theory/figure/length_same.png
  slides/information-theory/figure/length_var.png
  slides/information-theory/figure/multiclass-predictive.png
  slides/information-theory/figure/multinoulli.png
  slides/information-theory/figure/mutualinformation.pdf
  slides/information-theory/figure/quants.png
  slides/information-theory/figure/reverse_kl.png
  slides/information-theory/figure/shift.png
  slides/information-theory/figure/xent_pq.png
  slides/information-theory/figure/xent_qp.png
  slides/information-theory/figure_man/KL-log-diff.png
  slides/information-theory/figure_man/entropy-uniform.png
  slides/information-theory/figure_man/entropy.png
  slides/information-theory/rsrc/ggsave-1.R
  slides/information-theory/rsrc/ggsave-7.R
  slides/information-theory/rsrc/make_correlation_plot.R
  slides/information-theory/rsrc/make_entropy_plot.R
  slides/information-theory/rsrc/make_entropy_uniform_plot.R
  slides/information-theory/rsrc/make_kl_log_diff_plot.R
  slides/information-theory/slides-info-entropy.tex
  slides/information-theory/slides-info-kl.tex
  slides/information-theory/slides-info-mutual-info.tex
  slides/information-theory/slides-info-sourcecoding.tex
Labels: hiwi, chap-info-theory

#716 exercise eval 3 + knn
  exercises-pdf/ex_eval_3.pdf
  exercises-pdf/sol_eval_3.pdf
  exercises/evaluation/ex_eval_3.Rnw
  exercises/evaluation/ex_rnw/ex_roc_2.Rnw
  exercises/evaluation/ex_rnw/sol_roc_2.Rnw
  exercises/evaluation/sol_eval_3.Rnw
  exercises/knn/ex_rnw/ex_knn_from_scratch.Rnw
  exercises/knn/ex_rnw/ex_knn_manh.Rnw
  exercises/knn/ex_rnw/ex_trees_1.Rnw
  exercises/knn/ex_rnw/sol_knn_from_scratch.R
  exercises/knn/ex_rnw/sol_knn_manh.Rnw
  exercises/knn/ex_rnw/sol_trees_1.Rnw
  exercises/supervised-classification/ex_rnw/ex_knn_manh.Rnw
  exercises/supervised-classification/ex_rnw/sol_knn_manh.Rnw
  exercises/supervised-regression/ex_rnw/ex_knn_manh.Rnw
  exercises/supervised-regression/ex_rnw/sol_knn_manh.Rnw
Labels: chap-eval, exercises, chap-knn

#713 IC week #8 (CART)
  exercises/trees/ex_rnw/ex_ic_cart.Rnw
  exercises/trees/ex_rnw/ex_research_group_cart.Rnw
  exercises/trees/ex_rnw/sol_research_group_cart.Rnw
  exercises/trees/ic_cart.Rnw
  exercises/trees/ic_sol_cart.Rnw
Labels: hiwi, inv-classroom

#722 changed question about AUC=0
  quizzes/Chapter-4-5-Measures-Cla_78585898_20210702-1324.csv
Labels: inv-classroom

#720 added new notation
  slides/evaluation/slides-evaluation-generr.tex
  slides/evaluation/slides-evaluation-measures-regression.tex
  slides/evaluation/slides-evaluation-overfitting-underfitting.tex
  slides/evaluation/slides-evaluation-resampling-1.tex
  slides/evaluation/slides-evaluation-resampling-2.tex
  slides/evaluation/slides-evaluation-test.tex
  slides/evaluation/slides-evaluation-train.tex
  slides/ml-basics/slides-basics-learner.tex
Labels: chap-eval, hiwi

#724 drafted test exam
  exercises/testexam/ex_rnw/ex_knn_gower.Rnw
  exercises/testexam/ex_rnw/ex_lda_qda.Rnw
  exercises/testexam/ex_rnw/ex_poly.Rnw
  exercises/testexam/ex_rnw/ex_roc_island.Rnw
  exercises/testexam/ex_rnw/sol_knn_gower.Rnw
  exercises/testexam/ex_rnw/sol_lda_qda.Rnw
  exercises/testexam/ex_rnw/sol_poly.Rnw
  exercises/testexam/ex_rnw/sol_roc_island.Rnw
  exercises/testexam/ex_testexam.Rnw
  exercises/testexam/sol_testexam.Rnw
Labels: hiwi
