Repository slds-lmu/lecture_i2ml, pull requests merged in 2021-11, with the labels that each got.

#683 fixed typo (epsilon rather than a for logbarrier loss)
  slides-pdf/slides-advriskmin-regression-further-losses.pdf
  slides/advriskmin/slides-advriskmin-regression-further-losses.tex
Labels: chap-advriskmin

#682 IC2: Regression
  exercises/supervised-regression/ex_rnw/ex_research-group.Rnw
  exercises/supervised-regression/ic_regression.Rnw
  quizzes/IC-Week-2-research-group_76749008_20211101-2214.csv
Labels: hiwi, inv-classroom

#656 set up exercise regression anew
  exercises-pdf/ex_regression.pdf
  exercises-pdf/sol_regression.pdf
  exercises/supervised-regression/collection_regression.Rnw
  exercises/supervised-regression/ex_regression.Rnw
  exercises/supervised-regression/ex_rnw/Rplots.pdf
  exercises/supervised-regression/ex_rnw/ex_knn_lm.Rnw
  exercises/supervised-regression/ex_rnw/ex_lm_abalone.Rnw
  exercises/supervised-regression/ex_rnw/ex_lrn.Rnw
  exercises/supervised-regression/ex_rnw/ex_polynomial.Rnw
  exercises/supervised-regression/ex_rnw/ex_regr_losses.Rnw
  exercises/supervised-regression/ex_rnw/sol_knn_lm.R
  exercises/supervised-regression/ex_rnw/sol_lm_abalone.R
  exercises/supervised-regression/ex_rnw/sol_lm_abalone.Rnw
  exercises/supervised-regression/ex_rnw/sol_lrn.Rnw
  exercises/supervised-regression/ex_rnw/sol_lrn.tex
  exercises/supervised-regression/ex_rnw/sol_polynomial.Rnw
  exercises/supervised-regression/ex_rnw/sol_polynomial.tex
  exercises/supervised-regression/ex_rnw/sol_regr_losses.Rnw
  exercises/supervised-regression/ex_rnw/sol_regr_losses.tex
  exercises/supervised-regression/figure/abalone.JPG
  exercises/supervised-regression/sol_regression.Rnw
Labels: exercises, chap-regr

#687 SL bernoulli fix
  Errata.txt
  slides/advriskmin/slides-advriskmin-classification-bernoulli.tex
  slides/advriskmin/slides-advriskmin-max-likelihood-l2.tex
  slides/advriskmin/slides-advriskmin-max-likelihood-other.tex
  slides/cod/slides-cod-examples.tex
  slides/multiclass/slides-mc-binary-reduction.tex
  slides/multiclass/slides-mc-codebooks.tex
  slides/multiclass/slides-mc-losses.tex
  slides/nonlinear-svm/slides-nonlinsvm-uniapprox.tex
  slides/regularization/slides-regu-nonlin-bayes.tex
Labels: hiwi, chap-advriskmin

#685 Create IC3 on Logistic Regression
  exercises/supervised-classification/ex_rnw/ex_research-group-logreg.Rnw
  exercises/supervised-classification/ex_rnw/sol_research-group-logreg.Rnw
  exercises/supervised-classification/ic_classification-1.Rnw
  exercises/supervised-classification/ic_sol_classification_1.Rnw
  quizzes/IC-Week-3-research-group_76749008_20211109-0928.csv
Labels: hiwi, inv-classroom

#693 Fixed missing arrow for neural_net.png
  slides/multiclass/figure_man/neural_net.png
  slides/multiclass/slides-mc-softmax-regression.tex
Labels: hiwi

#691 IC4: LDA, QDA, NB
  exercises/supervised-classification/ex_rnw/ex_model-assumptions.Rnw
  exercises/supervised-classification/ex_rnw/sol_model-assumptions.Rnw
  exercises/supervised-classification/ic_classification_2.Rnw
  exercises/supervised-classification/ic_sol_classification_2.Rnw
Labels: hiwi, inv-classroom

#657 set up exercise classification anew
  exercises-pdf/ex_classification_1.pdf
  exercises-pdf/ex_classification_2.pdf
  exercises-pdf/sol_classification_1.pdf
  exercises-pdf/sol_classification_2.pdf
  exercises/supervised-classification/collection_classification.Rnw
  exercises/supervised-classification/ex_classification_1.Rnw
  exercises/supervised-classification/ex_classification_2.Rnw
  exercises/supervised-classification/ex_rnw/ex_lda_qda.Rnw
  exercises/supervised-classification/ex_rnw/ex_logreg_dec_boundaries_enhanced.Rnw
  exercises/supervised-classification/ex_rnw/ex_mlr_dec_boundaries.Rnw
  exercises/supervised-classification/ex_rnw/ex_naive_bayes.Rnw
  exercises/supervised-classification/ex_rnw/ex_softmax.Rnw
  exercises/supervised-classification/ex_rnw/sol_lda_qda.Rnw
  exercises/supervised-classification/ex_rnw/sol_logreg_dec_boundaries_enhanced.Rnw
  exercises/supervised-classification/ex_rnw/sol_mlr_dec_boundaries.R
  exercises/supervised-classification/ex_rnw/sol_naive_bayes.Rnw
  exercises/supervised-classification/ex_rnw/sol_naive_bayes.tex
  exercises/supervised-classification/ex_rnw/sol_softmax.Rnw
  exercises/supervised-classification/ex_rnw/sol_softmax.tex
  exercises/supervised-classification/figure/softmax_1.png
  exercises/supervised-classification/figure/softmax_2.png
  exercises/supervised-classification/figure/softmax_3.png
  exercises/supervised-classification/figure/softmax_4.png
  exercises/supervised-classification/sol_classification_1.Rnw
  exercises/supervised-classification/sol_classification_2.Rnw
Labels: chap-classif, exercises

#694 Create IC5 on Eval
  exercises/evaluation/ex_rnw/ex_basic_concepts.Rnw
  exercises/evaluation/ic_concepts.Rnw
Labels: hiwi, inv-classroom

#695 Updated and cleaned up source code + figures in chapter Multiclass Classification
  slides/multiclass/figure/iris_encoding.png
  slides/multiclass/figure/iris_scatter.png
  slides/multiclass/figure/onevsone_vs_onevsrest.png
  slides/multiclass/figure_man/Iris.png
  slides/multiclass/figure_man/scenario.png
  slides/multiclass/rsrc/ggsave-1.R
  slides/multiclass/rsrc/ggsave-2.R
  slides/multiclass/rsrc/ggsave-3.R
  slides/multiclass/rsrc/ggsave-4.R
  slides/multiclass/rsrc/make_iris_encoding_plot.R
  slides/multiclass/rsrc/make_iris_scatter_plot.R
  slides/multiclass/rsrc/make_onevsone_vs_onevsrest_plot.R
  slides/multiclass/rsrc/onevsone_vs_onevsrest.R
  slides/multiclass/slides-mc-binary-reduction.tex
  slides/multiclass/slides-mc-losses.tex
Labels: hiwi, chap-multiclass

#697 Added script to make ROC horizontal plots + Updated slides-evaluation-measures-classification-roc-space.tex.
  slides/evaluation/figure/roc_horizontal_step_1.png
  slides/evaluation/figure/roc_horizontal_step_2.png
  slides/evaluation/figure/roc_horizontal_step_3.png
  slides/evaluation/figure/roc_horizontal_step_4.png
  slides/evaluation/figure/roc_horizontal_step_5.png
  slides/evaluation/figure/roc_horizontal_step_6.png
  slides/evaluation/figure/roc_horizontal_step_7.png
  slides/evaluation/rsrc/make_roc_horizontal_plot.R
  slides/evaluation/slides-evaluation-measures-classification-roc-space.tex
Labels: hiwi

#698 added classif threshold
  cheatsheets/cheatsheet_notation/cheatsheet_notation.pdf
  cheatsheets/cheatsheet_notation/cheatsheet_notation.tex
Labels: hiwi

#702 IC5
  exercises/evaluation/ex_rnw/ex_train-test.Rnw
  exercises/evaluation/ex_rnw/sol_train-test.Rnw
  exercises/evaluation/ic_sol_train-test.Rnw
  exercises/evaluation/ic_train-test.Rnw
Labels: hiwi, inv-classroom

#700 new eval I exercise
  exercises-pdf/ex_eval_1.pdf
  exercises-pdf/ex_eval_2.pdf
  exercises-pdf/sol_eval_1.pdf
  exercises-pdf/sol_eval_2.pdf
  exercises/evaluation/ex_eval_1.Rnw
  exercises/evaluation/ex_eval_2.Rnw
  exercises/evaluation/ex_rnw/ex_regr_metrics.Rnw
  exercises/evaluation/ex_rnw/ex_train_test_split.Rnw
  exercises/evaluation/ex_rnw/figure/unnamed-chunk-1-1.pdf
  exercises/evaluation/ex_rnw/sol_regr_metrics.Rnw
  exercises/evaluation/ex_rnw/sol_train_test_split.Rnw
  exercises/evaluation/sol_eval_1.Rnw
  exercises/evaluation/sol_eval_2.Rnw
Labels: chap-eval, exercises
